### ISSUE TITLE
Fix function

### ISSUE THREAD

**Issue by hmcatee18** [sellinwood8/sds192-mp2#2]
We need to fix the function that creates the rep/dem winner and loser variables. As of now we are mutating these variables manually.

**Comment by hmcatee18** [comment]
Prof. Baumer said in class that this was too complicated to do, so we will keep this manual for now. Let's try to simplify a different part of our code with a function to receive an extra point for that!

**Comment by sellinwood8** [comment]
We ended up making a similar function that definitely would've benefitted from being able to assign values to variable arguments (which we struggled with before), but we made do. The function still simplifies the code a bit.
