### ISSUE TITLE
Fix winner_avg axis on bar graph

### ISSUE THREAD

**Issue by hmcatee18** [sellinwood8/sds192-mp2#3]
We need to fix the winner_avg axis on our bar graph. Right now the values on the axis are in billions, although the values in the dataset look correct. There might be something weird going on in the background that is adding or multiplying these values.

**Comment by sellinwood8** [comment]
I realized that what was being displayed on the y-axis was actually the sum of all contributions, not the average for each group, which explains why the numbers were so big.
